application: fishingforideas
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: idea.app

- url: /.*
  script: idea.app

- url: /logged/.*
  script: idea.app
  login: required

- url: /_ah/login_required
  script: idea.app

libraries:
- name: jinja2
  version: latest